### ISSUE TITLE
"Fatal: [Errno 2] No such file or directory; did you install phantomjs?\n"

### ISSUE THREAD

**Issue by deepakgd** [narainsagar/node-casperjs-aws-lambda#1]
How to fix this issue?

**Comment by narainsagar** [comment]
seems like you don't have phantomjs installed? or check & set your phantomjs path manually

try: `$ npm install -g phantomjs`

visit this issue link for more:
https://github.com/casperjs/casperjs/issues/861

**Comment by deepakgd** [comment]
wont work in aws lambda

**Comment by nikolaylukyanchuk** [comment]
+1 have the same problem

**Comment by deepakgd** [comment]
hi @nikolaylukyanchuk covert your casperjs code into phantomjs code and  provide node_module phantomjs path and filename in execFile. Sure it will work. i am using like this

**Comment by narainsagar** [comment]
@deepakgd @nikolaylukyanchuk Please pull the latest master - the issue is now been fixed in the PR #2 by @markni 👍

**Comment by prusanoff** [comment]
Hey @narainsagar  Great work, 
   however i am still having the same issue. 
   I have casper and phantom running locally just great. 
   however I am still getting the same issue with lambda
       `"Fatal: [Errno 2] No such file or directory; did you install phantomjs?\n"`
I have tried to point directly at exec in the root folder and it will not open it in aws lambda
I figured it might be in the casperjs
 then i have added phantom `PHANTOMJS_EXECUTABLE=pathtophantom` in the .env file and still no luck to get it up and running along with Casper.
I have logged all my directories and i did find it there however it still will not open it.
My question is where exactly is it being called

**Comment by prusanoff** [comment]
Hey @narainsagar
    I am on a mac, dose not that mean i need to change the type of phantomJS for linux since Im on a mac. I tried a different type of work around 

`var phantomjs = require('phantomjs');
var childOptions = {
    'PHANTOMJS_EXECUTABLE': phantomjs.path
  };
`

**Comment by narainsagar** [comment]
More discussion on same issue: #3

**Comment by narainsagar** [comment]
Fixed in PR #4
